
export const metadata = {
  title: 'Desenvolvedores',
  description: 'Generated by create next app'
};

import { RequireAuth } from '@/contexts/auth/RequireAuth';

export default function UserLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return <RequireAuth>{children}</RequireAuth>;
}
